### ISSUE TITLE
3.4.6 fails tests _intermittently_ 

### ISSUE THREAD

**Issue by genehack** [sass/perl-libsass#31] opened 2017-05-29 00:27 UTC
I've only observed the failure on macOs 10.12.5. 

Builds okay, then during `make test`, I see this: 

```
t/99_sass_specs.t ....... 3688/17631 Malformed UTF-8 character: \xb3 (unexpected continuation byte 0xb3, with no preceding start byte) in substitution (s///) at t/99_sass_specs.t line 64.
Malformed UTF-8 character (fatal) at t/99_sass_specs.t line 64.
# Looks like your test exited with 255 just after 4162.
t/99_sass_specs.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
```

Repeating `make test` gave a fully successful test run. 

Running `make test` a third time gave a failure on a different test number: 

```
t/99_sass_specs.t ....... 3055/17631 Malformed UTF-8 character: \xff\x7f\x0a (too short; 3 bytes available, need 13) in substitution (s///) at t/99_sass_specs.t line 64.
Malformed UTF-8 character: \xff\x7f\x0a (unexpected non-continuation byte 0x7f, immediately after start byte 0xff; need 13 bytes, got 1) in substitution (s///) at t/99_sass_specs.t line 64.
Malformed UTF-8 character (fatal) at t/99_sass_specs.t line 64.
# Looks like your test exited with 255 just after 4162.
t/99_sass_specs.t ....... Dubious, test returned 255 (wstat 65280, 0xff00)
```

**Comment by mgreter** [comment] 2017-05-29 09:14
Thanks for the report.

Unfortunately I could not reproduce it on my Yosemite VM.

Can you run the tests via
`make TEST_VERBOSE=1 test`

If above does not work, try
`perl t\99_sass_specs.t`

This should give you the exact spec that is failing.
You might need `make install` for the 2nd option.

**Comment by genehack** [comment] 2017-05-29 16:01
Here's the tail of the output with `TEST_VERBOSE=1`

```
ok 4162 - CSS: t/sass-spec/spec/libsass/base-level-parent/imported/basic-alone-itpl/input.scss
Malformed UTF-8 character: \xac (unexpected continuation byte 0xac, with no preceding start byte) in substitution (s///) at t/99_sass_specs.t line 64.
Malformed UTF-8 character (fatal) at t/99_sass_specs.t line 64.
# Looks like your test exited with 255 just after 4162.
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 13469/17631 subtests

Test Summary Report
-------------------
t/99_sass_specs.t     (Wstat: 65280 Tests: 4162 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 17631 tests but ran 4162.
Files=13, Tests=4930,  6 wallclock secs ( 0.79 usr  0.15 sys +  4.04 cusr  1.02 csys =  6.00 CPU)
Result: FAIL
Failed 1/13 test programs. 0/4930 subtests failed.
make: *** [test_dynamic] Error 255
```

(I'm assuming the thousands of lines of successful stuff above that isn't important, but if I'm wrong, let me know.)

Running with `TEST_VERBOSE=1` seems to make it a little more deterministic, in that it's failed three times in a row, and at the same spot... but with three different `Malformed UTF-8 character` errors. 


Also, in case it's helpful, the output of `perl -V` -- note that I'm running `5.26.0-RC1`: 

```
Summary of my perl5 (revision 5 version 26 subversion 0) configuration:
   
  Platform:
    osname=darwin
    osvers=16.5.0
    archname=darwin-2level
    uname='darwin irving.home.genehack.org 16.5.0 darwin kernel version 16.5.0: fri mar 3 16:52:33 pst 2017; root:xnu-3789.51.2~3release_x86_64 x86_64 i386 macbookpro11,1 darwin '
    config_args='-Dprefix=/opt/plenv/versions/5.26.0-RC1 -de -Dusedevel -A'eval:scriptdir=/opt/plenv/versions/5.26.0-RC1/bin''
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.12 -fno-strict-aliasing -pipe -fstack-protector-strong -I/opt/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.12 -fno-strict-aliasing -pipe -fstack-protector-strong -I/opt/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib -L/opt/local/lib'
    libpth=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib /usr/local/lib /opt/local/lib /usr/lib
    libs=-lpthread -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.12 -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Locally applied patches:
    RC1
    Devel::PatchPerl 1.48
  Built under darwin
  Compiled at May 11 2017 19:56:10
  %ENV:
    PERL_CPANM_OPT="--skip-installed --prompt"
    PERL_MM_USE_DEFAULT="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /opt/plenv/versions/5.26.0-RC1/lib/perl5/site_perl/5.26.0/darwin-2level
    /opt/plenv/versions/5.26.0-RC1/lib/perl5/site_perl/5.26.0
    /opt/plenv/versions/5.26.0-RC1/lib/perl5/5.26.0/darwin-2level
    /opt/plenv/versions/5.26.0-RC1/lib/perl5/5.26.0
    .
```

**Comment by mgreter** [comment] 2017-05-29 16:10
Thanks for the feedback. Unfortunately I think this still doesn't show in which spec the error happens. Since yesterday this error also pops up in cpan test matrix, but I strangely haven't been able to reproduce it on any of my systems. So would be glad if you would be willing to debug it a bit more.

In `t/99_sass_specs.t` around line 218 there is this commented line: `# warn $spec->{file};`
Could you activate that one and see if you get another path between the last `ok` and the error?

**Comment by mgreter** [comment] 2017-05-29 16:23
Also helpfull would be a complete stack trace, which you should get by calling
`perl -d:Confess t/99_sass_specs.t` (may needs to install Devel::Confess first)

**Comment by genehack** [comment] 2017-05-29 16:28
Here is with the warning turned on: 

```
t/sass-spec/spec/libsass/base-level-parent/imported/basic-alone-itpl/input.scss at t/99_sass_specs.t line 218.
ok 4162 - CSS: t/sass-spec/spec/libsass/base-level-parent/imported/basic-alone-itpl/input.scss
Malformed UTF-8 character: \x9b (unexpected continuation byte 0x9b, with no preceding start byte) in substitution (s///) at t/99_sass_specs.t line 64.
Malformed UTF-8 character (fatal) at t/99_sass_specs.t line 64.
# Looks like your test exited with 255 just after 4162.
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 13469/17631 subtests
```

I did a bit of ad hoc data dumping, and it looks like the error arises as a consequence of this line with that spec file:

```
eq_or_diff ($spec->err, $spec->stderr, "Errors: " . $spec->file);
```

**Comment by genehack** [comment] 2017-05-29 16:30
Here's the `Devel::Confess` output -- not very useful, I'm afraid:

```
        SPEC::css(SPEC=HASH(0x7f8dfe897840)) called at t/99_sass_specs.t line 392
ok 1816 - CSS: t/sass-spec/spec/libsass-closed-issues/issue_2304/input.scss
ok 1817 - Errors: t/sass-spec/spec/libsass-closed-issues/issue_2304/input.scss
ok 1818 - Warnings: t/sass-spec/spec/libsass-closed-issues/issue_2304/input.scss
t/sass-spec/spec/libsass-closed-issues/issue_2307/input.scss at t/99_sass_specs.t line 218.
        SPEC::execute(SPEC=HASH(0x7f8dfe897960)) called at t/99_sass_specs.t line 179
        SPEC::css(SPEC=HASH(0x7f8dfe897960)) called at t/99_sass_specs.t line 392
[1]    73750 segmentation fault  perl -d:Confess t/99_sass_specs.t
```

**Comment by genehack** [comment] 2017-05-29 16:30
I have to AFK for probably a big chunk of the day now, but I'll be back online later tonight. I'm on `irc.perl.org` if it would be quicker to hop into a common channel and pair up that way...

**Comment by mgreter** [comment] 2017-05-29 20:37
The hint with the used perl version finally enabled me to reproduce the issue. The problem is unfortunately deeper down in libsass. It is related to how the error indicator is generated in libsass. But there are multiple parts involved to trigger this.

sass_context.cpp ~ 91
```
msg_stream << ">> " << std::string(line_beg + move_in, line_end - shorten) << "\n";
```

The problem is that `e.pstate.src` is not set correctly, so the alogrithm fails and the line above returns out of bound memory. I guess the reason it is not set is due to the fact that the error is thrown from selector interpolation parsing. I've come up with a hotfix which should fix this issue and improve output under these condition.

```diff
--- "libsass/src/parser.cpp"
+++ "libsass/src/parser.cpp"
@@ -2934,6 +2934,7 @@ namespace Sass {
     if (left_subpos && ellipsis_left) left = ellipsis + left.substr(left_subpos);
     if (right_subpos && ellipsis_right) right = right.substr(right_subpos) + ellipsis;
     // now pass new message to the more generic error function
+    if (source == NULL || *source == 0) source = pstate.src;
     error(msg + prefix + quote(left) + middle + quote(right), pstate);
   }
 ```

I see now that the implementation can fail if actual utf8 characters are part of the error line. So the above only fixed the common case (should cover 99%), but is not really fully fixing it.

Could you try to apply this patch to libsass and see if tests pass with it?

Thanks!

**Comment by genehack** [comment] 2017-05-30 04:04
With that patch applied, tests have passed three times in a row! \o/

**Comment by mgreter** [comment] 2017-05-30 08:09
Great, thanks for testing. Will create a PR with libsass and release a new perl-libsass version "soonish". Will leave this ticket open until fixed.

To be clear, this is not a "big" problem and has existed in all previous versions. So you could just ignore these test failures if you really want to use CSS::Sass 3.4.6 (otherwise you probably want to stick to 3.4.5 for now).

**Comment by genehack** [comment] 2017-05-30 16:09
No worries, I already went ahead with the install once I saw how the tests were failing. 8^)

**Comment by mgreter** [comment] 2018-01-20 01:19
Closing as this should've been fixed by https://github.com/sass/libsass/pull/2541

**Closed by mgreter** 2018-01-20 01:19 UTC
