### ISSUE TITLE
"Segmentation fault: 11" with @extend?

### ISSUE THREAD

**Issue by jhthorsen** [sass/perl-libsass#17] opened 2016-02-22 08:28 UTC
I'm trying to compile https://github.com/Dogfalo/materialize with CSS::Sass, but I'm getting "Segmentation fault: 11" in OSX 10.11.4, Perl v5.22.0 and CSS::Sass 3.3.0.

The way to reproduce it is:

```
git clone https://github.com/Dogfalo/materialize.git
cd materialize
perl test.pl
```

The content of test.pl:
```
#!/usr/bin/env perl
use strict;
use warnings;
use CSS::Sass ();

CSS::Sass::sass_compile(<<'HERE', include_paths => ['sass']);
@charset "UTF-8";
@import "components/color";
@import "components/variables";
@import "components/cards";
@import "components/buttons";
HERE
```

I've tried different things, but it seems like I'm able to compile it, if I comment out ```@extend .btn;``` in https://github.com/Dogfalo/materialize/blob/master/sass/components/_buttons.scss#L185

**Comment by mgreter** [comment] 2016-02-22 10:21
Pretty sure this is related to libsass directly and probably a direct duplicate of https://github.com/sass/libsass/issues/1916. Therefore closing this and tracking upstream. If you think this is a different error, feel free to open an issue directly with libsass. If you want to get it solved faster please provide a standalone and reduced test case as we normally do not dig into other people frameworks. Thanks!

**Closed by mgreter** 2016-02-22 10:21 UTC

**Comment by jhthorsen** [comment] 2016-02-22 11:04
Thank you! Yeah, that sounds spot on.

**Comment by mgreter** [comment] 2016-02-22 16:09
OK, hope we can get a fix out soon, but don't quote me on that ;)
